### ISSUE TITLE
Android crash on shutdown

### ISSUE THREAD

**Issue by mscottwvc** [google/bumble#86] opened 2022-11-28 20:37 UTC
I think this bug is probably on the emulator side, but I havent found the correct team to contact for that so if you know please let me know, so I thought I would at least start here.

Scenario:  
I can successfully create an hci bridge to the android emulator and everything works, awesome job bumble team!
The problem is I cant find anyway to close down the the emulator without it crashing once this link has been established, here are some things I have tried (they all end up with the emulator crashing):

-  Closing emulator
-  Sending a shutdown command to the emulator
-  Disabling bluetooth and then trying the two above methods of closing the emulator.
-  Closing the bumble process

I used to get a popup on my linux box with more crash details, but I must have checked some box to send them automatically or something because I dont get this box anymore (tried android reinstall but no change), the only output I have is from my console and it is not helpful just shows a small stack trace of hex addresses.  I have tried multiple emulators and android versions, but they all crash.

Is there any way to send a command to the emulator to stop the vhci forward / root canal thing (in hopes that after that it wont crash on shutdown)?

Any suggestions are greatly appreciated, thanks.

**Comment by jpcottin** [comment] 2022-12-01 01:17
Thank you, @barbibulle 

Hi @mscottwvc 
This is an interesting bug, and as it crashes the Android emulator. I'd suggest you to file a bug to the Android Emulator (where I can triage it) .

Before doing this, a great way to get more information of those crashes would be to get some verbose log from the emulator.

`emulator -avd {YOUR_AVD} -show-kernel -verbose -logcat *:V -logcat-output logcat.txt > kernel.txt`


It will start the standalone emulator, and keep a verbose logcat in the file logcat.txt and a kernel debug in kernel.txt 

Then please report a bug via Android Studio. Open a bug report from Android Studio by selecting `Help > Submit Feedback`. This is the easiest way to start a bug because it populates the bug report .  It will help triaging if could

- mention in the title that this is about  a crash in the Android Emulator while using Bumble
- select `Android Public Tracker > App Development > Android Studio > Emulator` in the Component.
- mention this github issue number (for cross reference)
- add the kernel.txt and logcat.txt file generated when you reproduce the crash with the emulator ( when launching it with the command above)

**Comment by mscottwvc** [comment] 2022-12-01 16:43
Thanks @barbibulle and @jpcottin - This was very helpful!

I submitted the bug report, the id is 260968394

I also submitted another issue I have been working on, not sure if you are able to Triage this one as well, its id is 260963061.  Its a bug when a USB device is passed directly to Qemu side of the emulator and on emulator close the emulator crashes every time, though it crashes at the very end after it successfully creates the snapshot capture.

**Comment by jpcottin** [comment] 2023-02-03 23:14
Thank you,  @mscottwvc

The conditions of the crash in the Android emulator were understood and fixed in the version 32. The version 32 has been already available via SDK Manager in the Beta channel (32.1.10 right now), but during February the emulator 32 will go from "beta to stable), and starting with version 32.1.11 the SDK manager will deliver emulator 32 in the "stable track".

With this version, the emulator will not crash anymore on shutdown.

**Comment by barbibulle** [comment] 2023-02-03 23:56
Thanks JP. I'm closing this issue as fixed.

**Comment by mscottwvc** [comment] 2023-02-07 14:48
Thanks!

**Closed** 2023-02-07 14:49 UTC
